### ISSUE TITLE
"Dead" positions w/o profit, sell signal and volume but above stop-loss

### ISSUE THREAD

**Issue by heizie78** [iterativv/NostalgiaForInfinity#119] opened 2021-09-12 15:44 UTC
After some time running a custom version of NFI I see that some of my postions got quite "old". The reason is, that they are not in profit, but also did not receive a stop-loss/sell signal. Inbetween the volume of that pair has dropped as well, so that there is not much volatility. Some trades are in that state for more than a week. Issue now is that force-selling these positions would ruin the overall profit-%. Keeping these positions on the other side limits the capital available for new trades.
Any ideas how to deal with that?

**Comment by PeetCrypto** [comment] 2021-09-12 18:19
Maybe a Rebuy/dca of 50 - 100% positionsize the moment a next buy signal comes.

**Comment by heizie78** [comment] 2021-09-12 20:43
Yes, but unfortunately freqtrade doesn't support stacked trades yet.

**Comment by eSeR1805** [comment] 2021-09-13 07:55
So what are you asking actually? If all you care about is preserving although faking the overall profit % just `/delete <trade_id>` in telegram and manage manually

**Comment by heizie78** [comment] 2021-09-13 08:15
I think my question was pretty clear.
> Any ideas how to deal with that?

I don't see this as a "bug" nor do I ask to fake anything. I'm asking about experiences and how others deal with that situation.

**Comment by eSeR1805** [comment] 2021-09-13 08:22
Some forcesell some let the bot handle it however. It's a personal decision

**Comment by heizie78** [comment] 2021-09-13 09:14
Ya, I'm thinking to implement a kind of cleanup check to free capital. e.g.: once buy signals (on other pairs) start rising and there is not enough capital for new trades, sell some "dead positions" by certain criteria (even with neg. profit)

**Comment by eSeR1805** [comment] 2021-09-13 09:30
Sure. That can be a thing. But people will usually stick to singular examples and complain: "Hey we dropped COIN at -10% but now 1 day later it has recovered and would have even made some profit" or "Why did it sell now? It made a green candle" or whatever.
Indeed unclogging the capital can be a good thing. But there needs to be some more factors to that decision imo. If we drop a -10% that has basically bottomed out for a few 1-2% trades then you might loose more than just holding. Fuzzy area here hope I explained clear enough.

**Comment by heizie78** [comment] 2021-09-13 09:48
Hmm, one would have to decide for example by probabiltiy. How are the odds for a dead position to recover and whats the potential profit vs. potential profit from the "missed" buys due to lacking capital. Next question then would be how much capital should be freed. This all goes a little bit in the direction of edge trading. Easiest solution would be: DCA. add new capital. :-)

I agree, not an easy decision. Needs to be tested.

**Comment by Govind-S-B** [comment] 2021-11-27 02:01
Can we close this issue then ? I think the conclusion from the issue is clear

**Closed** 2021-11-27 10:18 UTC
